// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamE_SacramentPlanner.Data;

namespace TeamE_SacramentPlanner.Migrations
{
    [DbContext(typeof(TeamE_SacramentPlannerContext))]
    partial class TeamE_SacramentPlannerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("TeamE_SacramentPlanner.Models.MeetingProgram", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Benediction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClHymnName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClHymnNumber")
                        .HasColumnType("int");

                    b.Property<string>("Conducting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Invocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MusicalNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpHymnName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpHymnNumber")
                        .HasColumnType("int");

                    b.Property<string>("Presiding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SHymnName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SHymnNumber")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MeetingProgram");
                });

            modelBuilder.Entity("TeamE_SacramentPlanner.Models.Speaker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("MeetingID")
                        .HasColumnType("int");

                    b.Property<string>("SpeakerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpeakerType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Speaker");
                });
#pragma warning restore 612, 618
        }
    }
}
